# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build & Deploy all Environments (sample)
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Preview Env'
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(containerRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: 'install'
    - task: Npm@1
      displayName: 'npm run build'
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: Npm@1
      displayName: 'npm run export (next.js SSG)'
      inputs:
        command: 'custom'
        customCommand: 'run export'
    - task: AzureCLI@2
      displayName: 'Deploy to UAT Blob $web Container'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: 'az.storage.blob.upload-batch.sh'
        scriptArguments: '$(resourceGroup) $(storageAccountUAT) $(uploadDir)'
    - task: AzureCLI@2
      displayName: 'Deploy to Prod Blob $web Container'
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: 'az.storage.blob.upload-batch.sh'
        scriptArguments: '$(resourceGroup) $(storageAccountProd) $(uploadDir)'
    - task: Bash@3
      displayName: 'Purge Cache on UAT'
      inputs:
        filePath: 'az.stackpath.purge-cdn.sh'
        arguments: '$(cdnClientID) $(cdnClientSecret) $(cdnStackID) $(cdnUrlUAT)'
    - task: Bash@3
      displayName: 'Purge Cache on Prod'
      inputs:
        filePath: 'az.stackpath.purge-cdn.sh'
        arguments: '$(cdnClientID) $(cdnClientSecret) $(cdnStackID) $(cdnUrlProd)'
    
